apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openhab-dashboard.fullname" . }}-nginx
  labels:
    {{- include "openhab-dashboard.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
      listen       80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html;
          try_files $uri $uri/ /index.html;
      }
    }